name: traisformer
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  - pytorch=2.7
  - torchvision
  - torchaudio

  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - tqdm
  - pillow
  - opencv
  - cython
  - networkx
  - nltk
  - spacy
  - xgboost
  - lightgbm
  - catboost

  - pip

  - pip:
      - einops
      - ray
      - gpustat
      - fire
      - tensorboard
      - pytorch-lightning
      - torchmetrics
      - torchsde
      - sdeint
      - lambda-networks